name: CI

on:
  push:
    branches:
      - main

jobs:
  all-cli-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.17.0'
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: yarn lint:fix
